/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'primary': '#6eed53',
        'on-tertiary-container': '#564600',
        'error': '#ffb4ab',
        'tertiary-fixed': '#ffe175',
        'on-secondary-fixed': '#001b40',
        'on-secondary': '#002f66',
        'inverse-on-surface': '#002b75',
        'on-secondary-fixed-variant': '#004590',
        'background': '#001038',
        'surface-container-low': '#001849',
        'secondary-fixed': '#d7e2ff',
        'surface-variant': '#002f7e',
        'tertiary': '#f4d041',
        'on-error-container': '#ffdad6',
        'error-container': '#93000a',
        'surface-container-highest': '#002f7e',
        'on-error': '#690005',
        'inverse-primary': '#0e6e00',
        'secondary-fixed-dim': '#acc7ff',
        'on-surface': '#dae1ff',
        'on-tertiary': '#3b2f00',
        'on-tertiary-fixed': '#221b00',
        'outline-variant': '#3e4a39',
        'surface-tint': '#62e148',
        'on-primary-fixed': '#022200',
        'outline': '#879580',
        'on-tertiary-fixed-variant': '#554500',
        'on-primary-container': '#095400',
        'on-secondary-container': '#e6ecff',
        'surface-dim': '#001038',
        'surface-bright': '#053385',
        'tertiary-container': '#d6b424',
        'secondary': '#acc7ff',
        'surface-container-high': '#002567',
        'primary-container': '#51d039',
        'primary-fixed-dim': '#62e148',
        'primary-fixed': '#7efe62',
        'on-primary': '#043900',
        'surface-container': '#001c51',
        'surface-container-lowest': '#000c2d',
        'inverse-surface': '#dae1ff',
        'surface': '#001038',
        'on-background': '#dae1ff',
        'tertiary-fixed-dim': '#e7c435',
        'secondary-container': '#0068d4',
        'on-primary-fixed-variant': '#085300',
        'on-surface-variant': '#bdcbb4',
        'brand-primary': '#6eed53',
        'brand-secondary': '#acc7ff',
        'brand-tertiary': '#f4d041',
      },
      fontFamily: {
        'headline': ['Plus Jakarta Sans', 'sans-serif'],
        'body': ['Be Vietnam Pro', 'sans-serif'],
        'label': ['Space Grotesk', 'monospace'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [],
}
